### ISSUE TITLE
Use proper joins to render the index page

### ISSUE THREAD

**Issue by vrde** [vrde/letscheck#3]
# Problem

Loading data in the main view of the `content` app doesn't use joins. That's OK until we have few news, but doesn't scale.

This is how news are loaded in the `index` view:

https://github.com/vrde/letscheck/blob/5348d08a58a25403f2af60695252ef1a1339fde8/src/content/views.py#L13-L17

And this is where the news are rendered:

https://github.com/vrde/letscheck/blob/5348d08a58a25403f2af60695252ef1a1339fde8/src/content/templates/content/index.html#L84-L107

This doesn't scale because for each news we are hitting the db again to load derived data.

# Solution

Use [`select_related`](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#select-related) or [`prefetch_related`](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#prefetch-related) to do the actual joins and load all data in one or two round-trips to the database.

# Deliverable

A PR that fixes the issue and test that verifies that the news are correctly rendered in the template. A similar test that can be used as inspiration is the one used for the `triage` app.

https://github.com/vrde/letscheck/blob/5348d08a58a25403f2af60695252ef1a1339fde8/src/triage/tests.py#L66-L110

**Comment by lorrandal** [comment]
I can pick this issue up!
