### ISSUE TITLE
Aggregate data for index page

### ISSUE THREAD

**Issue by vrde** [vrde/letscheck#7]
Follow up of issue #3 

# Problem

Loading data in the main view of the `content` app doesn't aggregate data:

https://github.com/vrde/letscheck/blob/47f357681b8955bbb30291cd986036036a4a3a3c/src/content/templates/content/index.html#L97

This is `O(n)` because it generates a new query for each entry and it doesn't use the nice aggregate functions of SQL.

# Solution

I'm a bit rusty with Django, but [`annotate`](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#annotate) should do the job.

# Acceptance

Make sure (using the django debug toolbar) that the number of queries is not `O(n)`, where `n` is the number of news. Add a test that creates a news, attaches multiple cases to it, and verifies that the number displayed in the page is correct.

**Comment by lorrandal** [comment]
im going for this
